// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageType.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Pb {

  /// <summary>Holder for reflection information generated from MessageType.proto</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class MessageTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for MessageType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessageTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFNZXNzYWdlVHlwZS5wcm90bxICcGIqaQoLTWVzc2FnZVR5cGUSDgoKQ3Jl",
            "YXRlUm9vbRAAEgwKCEpvaW5Sb29tEAESDQoJTGlzdFJvb21zEGQSEQoMUmVn",
            "aXN0ZXJOb2RlEMgBEg8KClVwZGF0ZVJvb20QyQESCQoEQ2hhdBDKAWIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Pb.MessageType), }, null));
    }
    #endregion

  }
  #region Enums
  public enum MessageType {
    /// <summary>
    ///  Shared
    /// </summary>
    CreateRoom = 0,
    JoinRoom = 1,
    /// <summary>
    ///  Master
    /// </summary>
    ListRooms = 100,
    /// <summary>
    ///  Game
    /// </summary>
    RegisterNode = 200,
    UpdateRoom = 201,
    Chat = 202,
  }

  #endregion

}

#endregion Designer generated code
